"""迁移与模型的一致性，以及降级路径。

第 2 天这两项是手工跑过的——「升级/降级/漂移检查全通过」，验完就丢了。
和第 2 天那批约束一样，这里把它们变成每次跑测试都会过一遍的东西。

**本文件的用例必须是同步的。** alembic 的 command 内部走 asyncio.run()，
在已经运行的事件循环里调用会直接抛 RuntimeError。（conftest 里的
prepared_test_database 夹具是同一个原因才写成同步的。）
"""

import asyncio

import asyncpg
import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.engine import make_url

# 第一周的业务表。alembic_version 不在这里面：它是 alembic 自己的记账表，
# 降级到 base 之后它仍然存在（否则下次就没法从 base 再升上来了）。
APP_TABLES = {"users", "workspaces", "workspace_members", "auth_sessions"}


async def _existing_app_tables(database_url: str) -> set[str]:
    """直接问 Postgres 现在有哪些业务表。

    不走 SQLAlchemy 的 inspect：这里要的就是绕过所有抽象层，看数据库的真实状态。
    """
    url = make_url(database_url)
    connection = await asyncpg.connect(
        host=url.host or "localhost",
        port=url.port or 5432,
        user=url.username,
        password=url.password,
        database=url.database,
    )
    try:
        rows = await connection.fetch(
            "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
        )
    finally:
        await connection.close()
    return {row["tablename"] for row in rows} & APP_TABLES


def test_models_and_migrations_do_not_drift(alembic_config: Config) -> None:
    """models.py 和迁移脚本必须描述同一个数据库。

    防的是：改了 app/db/models.py 但忘了生成迁移。这种漏改**所有测试都会绿**——
    测试库是照着迁移建的，应用读的也是迁移建的表，两边一致地缺着那一列。
    要等到连上真实的库、或者部署完了才炸。

    `alembic check` 在 alembic 1.9+ 提供，就是为 CI 场景设计的。
    env.py 里的 compare_type / compare_server_default 在这里同样生效，
    所以改字段类型、改默认值漏生成迁移也会被它抓到。
    """
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "app/db/models.py 和 migrations 对不上了——多半是改了模型没生成迁移。\n"
            '生成一条：python -m alembic revision --autogenerate -m "..."\n\n'
            f"{exc}"
        )


def test_downgrade_and_upgrade_round_trip(
    alembic_config: Config, test_database_url: str
) -> None:
    """降级到 base 再升回 head，表要真的消失又真的回来。

    不能只断言「downgrade 没抛异常」：一个空实现的 downgrade 也不抛异常，
    它会安静地把表全留在原地。而降级路径平时根本没人走，只有真出事要回滚版本
    的时候才会用到——那正是最不能出意外的时候，所以它必须每次都被跑一遍。

    这个用例会真的删掉测试库里的表再重建。安全性来自两点：库名以 `_test` 结尾
    （由 conftest 里的 prepared_test_database 断言过），以及用例结束时又回到了 head。
    """
    command.downgrade(alembic_config, "base")
    assert asyncio.run(_existing_app_tables(test_database_url)) == set(), (
        "降级到 base 之后业务表还在，说明降级函数是空的或漏了表"
    )

    command.upgrade(alembic_config, "head")
    assert asyncio.run(_existing_app_tables(test_database_url)) == APP_TABLES, (
        "升回 head 之后表不全，升级路径有问题"
    )
